# Generated by Django 5.1 on 2024-08-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('publish_date', models.DateField(verbose_name='Published Date')),
                ('generated_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_details', to='app.generatedcontent')),
            ],
        ),
    ]
