# Generated by Django 5.1 on 2024-08-27 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('youtube_link', models.URLField()),
                ('blog', models.TextField()),
                ('transcript', models.TextField()),
                ('summary', models.TextField()),
                ('publish_date', models.DateField(verbose_name='Published Date')),
                ('generated_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_details', to='app.generatedcontent')),
            ],
        ),
    ]
