# Generated by Django 5.1 on 2024-08-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_videodetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
